=== kilomo12/codifica/esercitazioni/esercitazione_casa_1.dtd
<!ELEMENT ROOT_doc (strutturale, figlio, figlia)>
<!ELEMENT strutturale (#PCDATA)>
<!ELEMENT figlio (figlia?)>
<!ELEMENT figlia (testo?)>
<!ELEMENT testo (titolo)>
<!ELEMENT titolo (#PCDATA)>

=== kilomo12/codifica/esercitazione_casa_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ROOT_doc SYSTEM "esercitazione_casa_1.dtd">
<!-- questo esercizio è stato fatto per controllare l'acquisizione delle competenze in codifica-->
<ROOT_doc>
    <strutturale></strutturale>
    <figlio><figlia></figlia></figlio>
    <figlia>
        <testo>
            <titolo>
                il titolo della mia opera è : 
                <![CDATA[ <h1>Voglio controllare se ho capito la lezione.</h1>]]>
            </titolo>
        </testo>
    </figlia>
</ROOT_doc>
