=== kilomo12/codifica/esercitazioni/esercitazione_1.dtd
<!ELEMENT root-element (strutturale, testuale, misto, element-empty?, element+)>
<!ELEMENT strutturale (element*)>
<!ELEMENT testuale (#PCDATA)>
<!ELEMENT misto (#PCDATA | element)*>
<!ELEMENT element-empty EMPTY>
<!ELEMENT element (#PCDATA | figlio)*>
<!ELEMENT figlio (#PCDATA)>

=== kilomo12/codifica/esercitazioni/esercitazione_1.xml
<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "esercitazione_1.dtd">
<?xml-stylesheet href="file.css" type="text/css"?> <!-- processing instruction -->
<!-- prove fatte a lezione il 13/03/2025 per spiegare le gerarchie -->
<root-element>
    <strutturale>
        <element></element>
        <element></element>
        <element></element>
    </strutturale>
    <testuale>testo di riferimento</testuale>
    <misto>
        questo è il contenuto misto
        <element>Mi trovo bello</element>
        questo il contenuto<element>contenuto</element> misto
    </misto>
    <element-empty/>
    <element>
        <figlio>elemento annidato del elemento element</figlio>
    </element>
</root-element>
